# Generated by Django 4.0.5 on 2022-06-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardapp', '0002_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(),
        ),
    ]
