# Generated by Django 4.0.5 on 2022-06-13 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awardapp', '0003_alter_profile_image_alter_project_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votes',
            name='project',
        ),
        migrations.AlterField(
            model_name='votes',
            name='content',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True),
        ),
        migrations.AlterField(
            model_name='votes',
            name='design',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True),
        ),
        migrations.AlterField(
            model_name='votes',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='awardapp.profile'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='usability',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True),
        ),
    ]
