# Generated by Django 4.0.5 on 2022-06-14 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awardapp', '0004_remove_votes_project_alter_votes_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='awardapp.project'),
        ),
    ]
